---
sensors:
  Bathroom Ceiling Light:
    event: Light
    alt_predicate_when_true: false
    logic:
      predicate: alter
      x: ceiling_light
      y: state
    reports: binary
    inverted: false
    record: all
    ignore_false: false
  Bathroom Motion Sensor 1:
    event: Presence
    alt_predicate_when_true: false
    logic:
      predicate: move
      x: user
      y: bathroom
    reports: binary
    inverted: false
    record: all
    ignore_false: false
  Bathroom Motion Sensor 2:
    event: Presence
    alt_predicate_when_true: false
    logic:
      predicate: move
      x: user
      y: bathroom
    reports: binary
    inverted: false
    record: all
    ignore_false: false
  Toilet Occupied:
    event: Toilet
    alt_predicate_when_true: false
    logic:
      predicate: alter
      x: toilet
      y: state
    reports: binary
    inverted: false
    record: all
    ignore_false: false
  Toilet Lid:
    event: Toilet
    alt_predicate_when_true: false
    logic:
      predicate: alter
      x: toilet
      y: state
    reports: binary
    inverted: true
    record: all
    ignore_false: false
  Bed Occupied LHS:
    event: Bed
    alt_predicate_when_true: false
    logic:
      predicate: alter
      x: bed
      y: state
    reports: binary
    inverted: false
    record: all
    ignore_false: false
  Bed Occupied RHS:
    event: Bed
    alt_predicate_when_true: false
    logic:
      predicate: alter
      x: bed
      y: state
    reports: binary
    inverted: false
    record: all
    ignore_false: false
  Bedroom Blinds Control:
    event: Blind
    alt_predicate_when_true: false
    logic:
      predicate: alter
      x: blind
      y: state
    reports: numerical_threshold
    threshold: 50
    inverted: false
    record: all
    ignore_false: false
  Bedroom Ceiling Light:
    event: Blind
    alt_predicate_when_true: false
    logic:
      predicate: alter
      x: ceiling_light
      y: state
    reports: binary
    inverted: false
    record: all
    ignore_false: false
  Bedroom Drawer 1:
   event: ClothesDrawer
   alt_predicate_when_true: false
   logic:
     predicate: alter
     x: drawer
     y: state
   reports: binary
   inverted: false
   record: all
   ignore_false: false
  Bedroom Drawer 2:
   event: ClothesDrawer
   alt_predicate_when_true: false
   logic:
     predicate: alter
     x: drawer
     y: state
   reports: binary
   inverted: false
   record: all
   ignore_false: false
  Bedroom Drawer 3:
   event: ClothesDrawer
   alt_predicate_when_true: false
   logic:
     predicate: alter
     x: drawer
     y: state
   reports: binary
   inverted: false
   record: all
   ignore_false: false
  Bedroom Drawer 4:
   event: ClothesDrawer
   alt_predicate_when_true: false
   logic:
     predicate: alter
     x: drawer
     y: state
   reports: binary
   inverted: false
   record: all
   ignore_false: false
  Bedroom Drawer 5:
   event: ClothesDrawer
   alt_predicate_when_true: false
   logic:
     predicate: alter
     x: drawer
     y: state
   reports: binary
   inverted: false
   record: all
   ignore_false: false
  Bedroom Drawer 6:
   event: ClothesDrawer
   alt_predicate_when_true: false
   logic:
     predicate: alter
     x: drawer
     y: state
   reports: binary
   inverted: false
   record: all
   ignore_false: false
  Bedroom Wardrobe 1:
   event: ClothesWardrobe
   alt_predicate_when_true: false
   logic:
     predicate: alter
     x: wardrobe
     y: state
   reports: binary
   inverted: false
   record: all
   ignore_false: false
  Bedroom Wardrobe 2:
   event: ClothesWardrobe
   alt_predicate_when_true: false
   logic:
     predicate: alter
     x: wardrobe
     y: state
   reports: binary
   inverted: false
   record: all
   ignore_false: false
  Bedroom Motion Sensor 1:
    event: Presence
    alt_predicate_when_true: false
    logic:
      predicate: move
      x: user
      y: bedroom
    reports: binary
    inverted: false
    record: all
    ignore_false: false
  Bedroom Motion Sensor 2:
    event: Presence
    alt_predicate_when_true: false
    logic:
      predicate: move
      x: user
      y: bedroom
    reports: binary
    inverted: false
    record: all
    ignore_false: false
  Dining Motion Sensor 1:
    event: Presence
    alt_predicate_when_true: false
    logic:
      predicate: move
      x: user
      y: dining
    reports: binary
    inverted: false
    record: all
    ignore_false: false
  Dining Motion Sensor 2:
    event: Presence
    alt_predicate_when_true: false
    logic:
      predicate: move
      x: user
      y: dining
    reports: binary
    inverted: false
    record: all
    ignore_false: false
  Dining Chair 1 Occupied:
    event: DiningChair
    alt_predicate_when_true: false
    logic:
      predicate: alter
      x: dining_chair
      y: state
    reports: binary
    inverted: true
    record: all
    ignore_false: false
  Dining Chair 2 Occupied:
    event: DiningChair
    alt_predicate_when_true: false
    logic:
      predicate: alter
      x: dining_chair
      y: state
    reports: binary
    inverted: true
    record: all
    ignore_false: false
  Lounge Blinds Control:
    event: Blind
    alt_predicate_when_true: false
    logic:
      predicate: alter
      x: blind
      y: state
    reports: numerical_threshold
    threshold: 50
    inverted: false
    record: all
    ignore_false: false
  Lounge Ceiling Light:
    event: Light
    alt_predicate_when_true: false
    logic:
      predicate: alter
      x: ceiling_light
      y: state
    reports: binary
    inverted: false
    record: all
    ignore_false: false
  Lounge Motion Sensor 1:
    event: Presence
    alt_predicate_when_true: false
    logic:
      predicate: move
      x: user
      y: lounge
    reports: binary
    inverted: false
    record: all
    ignore_false: false
  Sofa Occupied LHS:
    event: Sofa
    alt_predicate_when_true: false
    logic:
      predicate: alter
      x: sofa
      y: state
    reports: binary
    inverted: true
    record: all
    ignore_false: false
  Sofa Occupied RHS:
    event: Sofa
    alt_predicate_when_true: false
    logic:
      predicate: alter
      x: sofa
      y: state
    reports: binary
    inverted: false
    record: all
    ignore_false: false
  Lounge TV Power:
    event: TV
    alt_predicate_when_true: false
    logic:
      predicate: alter
      x: TV
      y: state
    reports: energy
    threshold: 30
    inverted: false
    record: all
    ignore_false: false
  Kettle Pressure:
    event: Kettle
    alt_predicate_when_true: true
    logic:
      predicate: take
      alt_predicate: give
      x: user
      y: kettle
    reports: binary
    inverted: false
    record: all
    ignore_false: false
  Kettle Trigger:
    event: Kettle
    alt_predicate_when_true: true
    logic:
      predicate: take
      alt_predicate: give
      x: user
      y: kettle
    reports: binary
    inverted: false
    record: all
    ignore_false: false
  Kettle Power:
    event: Kettle
    alt_predicate_when_true: false
    logic:
      predicate: alter
      x: kettle
      y: state
    reports: energy
    threshold: 1200
    inverted: false
    record: all
    ignore_false: false
  Kitchen Tap Power:
    event: Tap
    alt_predicate_when_true: false
    logic:
      predicate: alter
      x: tap
      y: state
    reports: binary
    inverted: false
    record: all
    ignore_false: false
  Oven Door:
    event: Oven
    alt_predicate_when_true: false
    logic:
      predicate: alter
      x: oven
      y: state
    reports: binary
    inverted: true
    record: all
    ignore_false: false
  Fridge Door:
    event: Fridge
    alt_predicate_when_true: false
    logic:
      predicate: alter
      x: fridge
      y: state
    reports: binary
    inverted: true
    record: all
    ignore_false: false
  Kitchen Base Cabinet 1:
    event: MiscCabinet
    alt_predicate_when_true: false
    logic:
      predicate: alter
      x: cabinet
      y: state
    reports: binary
    inverted: true
    record: all
    ignore_false: false
  Kitchen Base Cabinet 2:
    event: MiscCabinet
    alt_predicate_when_true: false
    logic:
      predicate: alter
      x: cabinet
      y: state
    reports: binary
    inverted: true
    record: all
    ignore_false: false
  Kitchen Base Cabinet 3:
    event: MiscCabinet
    alt_predicate_when_true: false
    logic:
      predicate: alter
      x: cabinet
      y: state
    reports: binary
    inverted: true
    record: all
    ignore_false: false
  Kitchen Base Cabinet 4:
    event: Fridge
    alt_predicate_when_true: false
    logic:
      predicate: alter
      x: fridge
      y: state
    reports: binary
    inverted: true
    record: all
    ignore_false: false
  Kitchen Base Cabinet 5:
    event: MiscCabinet
    alt_predicate_when_true: false
    logic:
      predicate: alter
      x: cabinet
      y: state
    reports: binary
    inverted: true
    record: all
    ignore_false: false
  Kitchen Wall Cabinet 1:
    event: DinnerwareCabinet
    alt_predicate_when_true: false
    logic:
      predicate: alter
      x: cabinet
      y: state
    reports: binary
    inverted: true
    record: all
    ignore_false: false
  Kitchen Wall Cabinet 2:
    event: DrinkwareCabinet
    alt_predicate_when_true: false
    logic:
      predicate: alter
      x: cabinet
      y: state
    reports: binary
    inverted: true
    record: all
    ignore_false: false
  Kitchen Wall Cabinet 3:
    event: FoodCabinet
    alt_predicate_when_true: false
    logic:
      predicate: alter
      x: cabinet
      y: state
    reports: binary
    inverted: true
    record: all
    ignore_false: false
  Kitchen Wall Cabinet 4:
    event: FoodCabinet
    alt_predicate_when_true: false
    logic:
      predicate: alter
      x: cabinet
      y: state
    reports: binary
    inverted: true
    record: all
    ignore_false: false
  Kitchen Wall Cabinet 5:
    event: MiscCabinet
    alt_predicate_when_true: false
    logic:
      predicate: alter
      x: cabinet
      y: state
    reports: binary
    inverted: true
    record: all
    ignore_false: false
  Kitchen Drawer Bottom:
    event: MiscDrawer
    alt_predicate_when_true: false
    logic:
      predicate: alter
      x: drawer
      y: state
    reports: binary
    inverted: true
    record: all
    ignore_false: false
  Kitchen Drawer Middle:
    event: MiscDrawer
    alt_predicate_when_true: false
    logic:
      predicate: alter
      x: drawer
      y: state
    reports: binary
    inverted: true
    record: all
    ignore_false: false
  Kitchen Drawer Top:
    event: CutleryDrawer
    alt_predicate_when_true: false
    logic:
      predicate: alter
      x: drawer
      y: state
    reports: binary
    inverted: true
    record: all
    ignore_false: false
  Kitchen Motion Sensor 1:
    event: Presence
    alt_predicate_when_true: false
    logic:
      predicate: move
      x: user
      y: kitchen
    reports: binary
    inverted: false
    record: all
    ignore_false: false
  Kitchen Motion Sensor 2:
    event: Presence
    alt_predicate_when_true: false
    logic:
      predicate: move
      x: user
      y: kitchen
    reports: binary
    inverted: false
    record: all
    ignore_false: false
  Kitchen Ceiling Light:
    event: Light
    alt_predicate_when_true: false
    logic:
      predicate: alter
      x: ceiling_light
      y: state
    reports: binary
    inverted: false
    record: all
    ignore_false: false
  Hall Motion Sensor 1:
    event: Presence
    alt_predicate_when_true: false
    logic:
      predicate: move
      x: user
      y: hall
    reports: binary
    inverted: false
    record: all
    ignore_false: false
