version: '3.4'

services:
  ralt_lorex_stream:
    container_name: ralt_lorex_stream
    tty: true
    entrypoint: /home/root/start.sh
    network_mode: "host"
    image: ronsm/ralt-lorex-stream
    build:
      context: .
      dockerfile: ralt-lorex-stream/Dockerfile
    volumes:
      - ./ralt-lorex-stream/shared:/home/sandbox/shared
    environment:
      ROS_MASTER_URI: '${HSR_MASTER_URI}'
      ROS_MASTER_HOSTNAME: '${HSR_HOSTNAME}'
      ROS_IP: ${ROS_IP}

  ralt_semantic_event_logger:
    container_name: ralt_semantic_event_logger
    tty: true
    entrypoint: /home/root/start.sh
    network_mode: "host"
    image: ronsm/ralt-semantic-event-logger
    build:
      context: .
      dockerfile: ralt-semantic-event-logger/Dockerfile
    volumes:
      - ./ralt-semantic-event-logger/config:/home/sandbox/config
      - ./ralt-signalman/output:/home/sandbox/output
    environment:
      ROS_MASTER_URI: '${HSR_MASTER_URI}'
      ROS_MASTER_HOSTNAME: '${HSR_HOSTNAME}'
      ROS_IP: ${ROS_IP}
  
  ralt_apple_watch_publisher:
    container_name: ralt_apple_watch_publisher
    tty: true
    entrypoint: /home/root/start.sh
    network_mode: "host"
    image: ronsm/ralt-apple-watch-publisher
    build:
      context: .
      dockerfile: ralt-apple-watch-publisher/Dockerfile
    volumes:
      - ./ralt-signalman/output:/home/sandbox/output
    environment:
      ROS_MASTER_URI: '${HSR_MASTER_URI}'
      ROS_MASTER_HOSTNAME: '${HSR_HOSTNAME}'
      ROS_IP: ${ROS_IP}
    
  ralt_signalman:
    container_name: ralt_signalman
    tty: true
    entrypoint: /home/root/start.sh
    network_mode: "host"
    image: ronsm/ralt-signalman
    build:
      context: .
      dockerfile: ralt-signalman/Dockerfile
    volumes:
      - ./ralt-signalman/config:/home/sandbox/config
      - ./ralt-signalman/output:/home/sandbox/output
    environment:
      ROS_MASTER_URI: ${HSR_MASTER_URI}
      ROS_MASTER_HOSTNAME: '${HSR_HOSTNAME}'
      ROS_IP: ${ROS_IP}

  ralt_signalman_secondary:
    container_name: ralt_signalman_secondary
    tty: true
    entrypoint: /home/root/start.sh
    network_mode: "host"
    image: ronsm/ralt-signalman-secondary
    build:
      context: .
      dockerfile: ralt-signalman-secondary/Dockerfile
    volumes:
      - ./ralt-signalman/config:/home/sandbox/config
      - ./ralt-signalman/output:/home/sandbox/output
    environment:
      ROS_MASTER_URI: '${TIAGO_MASTER_URI}'
      ROS_MASTER_HOSTNAME: '${TIAGO_HOSTNAME}'
      ROS_IP: ${HSR_IP}

  ralt_signalman_dashboard:
    container_name: ralt_signalman_dashboard
    tty: true
    entrypoint: /home/root/start.sh
    network_mode: "host"
    image: ronsm/ralt-signalman-dashboard
    build:
      context: .
      dockerfile: ralt-signalman-dashboard/Dockerfile
    environment:
      ROS_MASTER_URI: '${HSR_MASTER_URI}'
      ROS_MASTER_HOSTNAME: '${HSR_HOSTNAME}'
      ROS_IP: ${ROS_IP}

  ralt_signalman_webcams:
    container_name: ralt_signalman_webcams
    tty: true
    entrypoint: /home/root/start.sh
    network_mode: "host"
    image: ronsm/ralt-signalman-webcams
    build:
      context: .
      dockerfile: ralt-signalman-webcams/Dockerfile
    volumes:
      - ./ralt-signalman/output:/home/sandbox/output
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
      - /dev/video2:/dev/video2
      - /dev/video3:/dev/video3
      - /dev/video4:/dev/video4
      - /dev/video5:/dev/video5
    environment:
      ROS_MASTER_URI: '${HSR_MASTER_URI}'
      ROS_MASTER_HOSTNAME: '${HSR_HOSTNAME}'
      ROS_IP: ${ROS_IP}

#  robot_har_mln:
#    container_name: robot_har_mln
#    tty: true
#    entrypoint: /home/root/start.sh
#    network_mode: "host"
#    image: ronsm/robot_har_mln
#    build:
#      context: .
#      dockerfile: robot-har-mln/Dockerfile
#    environment:
#      ROS_MASTER_URI: '${HSR_MASTER_URI}'
#      ROS_MASTER_HOSTNAME: '${HSR_HOSTNAME}'
#      ROS_IP: ${ROS_IP}
