version: '3'

services:
  sandbox:
    tty: true
    entrypoint: /home/root/start_stream.sh
    image: ronsm/ralt-lorex-stream
    build:
      context: .
      network: host
    volumes:
      - ./shared:/home/sandbox/shared
    environment:
      - ROS_MASTER_URI=http://192.168.1.130:11311/