version: '3'

services:
  sandbox:
    tty: true
    entrypoint: /home/root/start.sh
    image: ronsm/ralt-openhab
    build: .
    volumes:
      - ./shared:/home/sandbox/shared
    ports:
      # HTTP
      - 8080:8080
      # HTTPS
      - 8443:8443
    environment:
      - OPENHAB_HTTP_PORT=8080
      - OPENHAB_HTTPS_PORT=8443
      - USER_ID=9001
      - GROUP_ID=9001